// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import Accordion from "~/registry/new-york/ui/accordion";
import Alert from "~/registry/new-york/ui/alert";
import AlertDialog from "~/registry/new-york/ui/alert-dialog";
import AspectRatio from "~/registry/new-york/ui/aspect-ratio";
import Avatar from "~/registry/new-york/ui/avatar";
import Badge from "~/registry/new-york/ui/badge";
import Button from "~/registry/new-york/ui/button";
import Calendar from "~/registry/new-york/ui/calendar";
import Card from "~/registry/new-york/ui/card";
import Checkbox from "~/registry/new-york/ui/checkbox";
import Collapsible from "~/registry/new-york/ui/collapsible";
import Command from "~/registry/new-york/ui/command";
import ContextMenu from "~/registry/new-york/ui/context-menu";
import Dialog from "~/registry/new-york/ui/dialog";
import DropdownMenu from "~/registry/new-york/ui/dropdown-menu";
import HoverCard from "~/registry/new-york/ui/hover-card";
import Input from "~/registry/new-york/ui/input";
import Label from "~/registry/new-york/ui/label";
import Menubar from "~/registry/new-york/ui/menubar";
import NavigationMenu from "~/registry/new-york/ui/navigation-menu";
import Popover from "~/registry/new-york/ui/popover";
import Progress from "~/registry/new-york/ui/progress";
import RadioGroup from "~/registry/new-york/ui/radio-group";
import ScrollArea from "~/registry/new-york/ui/scroll-area";
import Select from "~/registry/new-york/ui/select";
import Separator from "~/registry/new-york/ui/separator";
import Sheet from "~/registry/new-york/ui/sheet";
import Skeleton from "~/registry/new-york/ui/skeleton";
import Slider from "~/registry/new-york/ui/slider";
import Switch from "~/registry/new-york/ui/switch";
import Table from "~/registry/new-york/ui/table";
import Tabs from "~/registry/new-york/ui/tabs";
import Textarea from "~/registry/new-york/ui/textarea";
import Toast from "~/registry/new-york/ui/toast";
import Toggle from "~/registry/new-york/ui/toggle";
import Tooltip from "~/registry/new-york/ui/tooltip";

export const Index: Record<string, any> = {
  "new-york": {
    accordion: {
      name: "accordion",
      type: "components:ui",
      registryDependencies: undefined,
      component: Accordion,
      files: ["src/registry/new-york/ui/accordion.tsx"],
    },
    alert: {
      name: "alert",
      type: "components:ui",
      registryDependencies: undefined,
      component: Alert,
      files: ["src/registry/new-york/ui/alert.tsx"],
    },
    "alert-dialog": {
      name: "alert-dialog",
      type: "components:ui",
      registryDependencies: ["button"],
      component: AlertDialog,
      files: ["src/registry/new-york/ui/alert-dialog-react.tsx"],
    },
    "aspect-ratio": {
      name: "aspect-ratio",
      type: "components:ui",
      registryDependencies: undefined,
      component: AspectRatio,
      files: ["src/registry/new-york/ui/aspect-ratio.tsx"],
    },
    avatar: {
      name: "avatar",
      type: "components:ui",
      registryDependencies: undefined,
      component: Avatar,
      files: ["src/registry/new-york/ui/avatar-vanilla.tsx"],
    },
    badge: {
      name: "badge",
      type: "components:ui",
      registryDependencies: undefined,
      component: Badge,
      files: ["src/registry/new-york/ui/badge.tsx"],
    },
    button: {
      name: "button",
      type: "components:ui",
      registryDependencies: undefined,
      component: Button,
      files: ["src/registry/new-york/ui/button.tsx"],
    },
    calendar: {
      name: "calendar",
      type: "components:ui",
      registryDependencies: ["button"],
      component: Calendar,
      files: ["src/registry/new-york/ui/calendar-qwikified.tsx"],
    },
    card: {
      name: "card",
      type: "components:ui",
      registryDependencies: undefined,
      component: Card,
      files: ["src/registry/new-york/ui/card.tsx"],
    },
    checkbox: {
      name: "checkbox",
      type: "components:ui",
      registryDependencies: undefined,
      component: Checkbox,
      files: ["src/registry/new-york/ui/checkbox.tsx"],
    },
    collapsible: {
      name: "collapsible",
      type: "components:ui",
      registryDependencies: undefined,
      component: Collapsible,
      files: ["src/registry/new-york/ui/collapsible.tsx"],
    },
    command: {
      name: "command",
      type: "components:ui",
      registryDependencies: ["dialog"],
      component: Command,
      files: ["src/registry/new-york/ui/command-react.tsx"],
    },
    "context-menu": {
      name: "context-menu",
      type: "components:ui",
      registryDependencies: undefined,
      component: ContextMenu,
      files: ["src/registry/new-york/ui/context-menu-react.tsx"],
    },
    dialog: {
      name: "dialog",
      type: "components:ui",
      registryDependencies: undefined,
      component: Dialog,
      files: ["src/registry/new-york/ui/dialog-react.tsx"],
    },
    "dropdown-menu": {
      name: "dropdown-menu",
      type: "components:ui",
      registryDependencies: undefined,
      component: DropdownMenu,
      files: ["src/registry/new-york/ui/dropdown-menu-react.tsx"],
    },
    "hover-card": {
      name: "hover-card",
      type: "components:ui",
      registryDependencies: undefined,
      component: HoverCard,
      files: ["src/registry/new-york/ui/hover-card-react.tsx"],
    },
    input: {
      name: "input",
      type: "components:ui",
      registryDependencies: undefined,
      component: Input,
      files: ["src/registry/new-york/ui/input.tsx"],
    },
    label: {
      name: "label",
      type: "components:ui",
      registryDependencies: undefined,
      component: Label,
      files: ["src/registry/new-york/ui/label.tsx"],
    },
    menubar: {
      name: "menubar",
      type: "components:ui",
      registryDependencies: undefined,
      component: Menubar,
      files: ["src/registry/new-york/ui/menubar-react.tsx"],
    },
    "navigation-menu": {
      name: "navigation-menu",
      type: "components:ui",
      registryDependencies: undefined,
      component: NavigationMenu,
      files: ["src/registry/new-york/ui/navigation-menu-react.tsx"],
    },
    popover: {
      name: "popover",
      type: "components:ui",
      registryDependencies: undefined,
      component: Popover,
      files: ["src/registry/new-york/ui/popover-react.tsx"],
    },
    progress: {
      name: "progress",
      type: "components:ui",
      registryDependencies: undefined,
      component: Progress,
      files: ["src/registry/new-york/ui/progress-qwikified.tsx"],
    },
    "radio-group": {
      name: "radio-group",
      type: "components:ui",
      registryDependencies: undefined,
      component: RadioGroup,
      files: ["src/registry/new-york/ui/radio-group-vanilla.tsx"],
    },
    "scroll-area": {
      name: "scroll-area",
      type: "components:ui",
      registryDependencies: undefined,
      component: ScrollArea,
      files: ["src/registry/new-york/ui/scroll-area-vanilla.tsx"],
    },
    select: {
      name: "select",
      type: "components:ui",
      registryDependencies: undefined,
      component: Select,
      files: ["src/registry/new-york/ui/select-vanilla.tsx"],
    },
    separator: {
      name: "separator",
      type: "components:ui",
      registryDependencies: undefined,
      component: Separator,
      files: ["src/registry/new-york/ui/separator.tsx"],
    },
    sheet: {
      name: "sheet",
      type: "components:ui",
      registryDependencies: undefined,
      component: Sheet,
      files: ["src/registry/new-york/ui/sheet-react.tsx"],
    },
    skeleton: {
      name: "skeleton",
      type: "components:ui",
      registryDependencies: undefined,
      component: Skeleton,
      files: ["src/registry/new-york/ui/skeleton.tsx"],
    },
    slider: {
      name: "slider",
      type: "components:ui",
      registryDependencies: undefined,
      component: Slider,
      files: ["src/registry/new-york/ui/slider-vanilla.tsx"],
    },
    switch: {
      name: "switch",
      type: "components:ui",
      registryDependencies: undefined,
      component: Switch,
      files: ["src/registry/new-york/ui/switch-vanilla.tsx"],
    },
    table: {
      name: "table",
      type: "components:ui",
      registryDependencies: undefined,
      component: Table,
      files: ["src/registry/new-york/ui/table-react.tsx"],
    },
    tabs: {
      name: "tabs",
      type: "components:ui",
      registryDependencies: undefined,
      component: Tabs,
      files: ["src/registry/new-york/ui/tabs.tsx"],
    },
    textarea: {
      name: "textarea",
      type: "components:ui",
      registryDependencies: undefined,
      component: Textarea,
      files: ["src/registry/new-york/ui/textarea.tsx"],
    },
    toast: {
      name: "toast",
      type: "components:ui",
      registryDependencies: undefined,
      component: Toast,
      files: [
        "src/registry/new-york/ui/toast-react.tsx",
        "src/registry/new-york/ui/use-toast-react.ts",
        "src/registry/new-york/ui/toaster-qwikified.tsx",
      ],
    },
    toggle: {
      name: "toggle",
      type: "components:ui",
      registryDependencies: undefined,
      component: Toggle,
      files: ["src/registry/new-york/ui/toggle-vanilla.tsx"],
    },
    tooltip: {
      name: "tooltip",
      type: "components:ui",
      registryDependencies: undefined,
      component: Tooltip,
      files: ["src/registry/new-york/ui/tooltip-react.tsx"],
    },
  },
};
